# Generated by Django 3.1.3 on 2022-07-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ente', models.CharField(default='', max_length=12)),
                ('periodo', models.CharField(default='', max_length=6)),
                ('ficha', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=40)),
                ('dni', models.IntegerField(default=0)),
                ('cuil', models.IntegerField(default=0)),
                ('repa', models.IntegerField(default=0)),
                ('loca', models.IntegerField(default=0)),
                ('importe', models.FloatField(default=0)),
                ('detalle', models.CharField(default='', max_length=20)),
                ('afiliado', models.IntegerField(default=0)),
            ],
        ),
    ]
